#!/usr/bin/env python3
"""Generate an ideal beta-cristobalite SiO2 supercell for LAMMPS/ReaxFF.

This script is intentionally dependency-free. If you use ASE in your own
machine, you can read the produced .xyz/.data files with ASE afterwards.

Default: conventional diamond-like beta-cristobalite cell with 8 Si + 16 O
per cell. A 2x2x2 supercell gives 64 Si + 128 O = 192 atoms, matching the
small system in Niu et al. (2018).
"""
from __future__ import annotations

import argparse
import math
import random
from pathlib import Path
from typing import Iterable, List, Tuple

Vec = Tuple[float, float, float]

SI_MASS = 28.0855
O_MASS = 15.9994

# Conventional diamond cubic positions for the Si sublattice.
SI_BASIS_FRAC = [
    (0.0, 0.0, 0.0),
    (0.25, 0.25, 0.25),
    (0.0, 0.5, 0.5),
    (0.25, 0.75, 0.75),
    (0.5, 0.0, 0.5),
    (0.75, 0.25, 0.75),
    (0.5, 0.5, 0.0),
    (0.75, 0.75, 0.25),
]


def wrap(x: float, L: float) -> float:
    y = x % L
    if abs(y - L) < 1e-10:
        return 0.0
    return y


def min_image_delta(a: Vec, b: Vec, box: Vec) -> Vec:
    d = [b[k] - a[k] for k in range(3)]
    for k, L in enumerate(box):
        d[k] -= round(d[k] / L) * L
    return (d[0], d[1], d[2])


def norm(v: Vec) -> float:
    return math.sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2])


def add(a: Vec, b: Vec) -> Vec:
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def scale(v: Vec, s: float) -> Vec:
    return (v[0] * s, v[1] * s, v[2] * s)


def generate(a: float, reps: Tuple[int, int, int], jitter: float, seed: int) -> Tuple[List[str], List[Vec], Vec]:
    rng = random.Random(seed)
    nx, ny, nz = reps
    box = (a * nx, a * ny, a * nz)

    symbols: List[str] = []
    positions: List[Vec] = []

    # Build Si lattice.
    si_positions: List[Vec] = []
    for ix in range(nx):
        for iy in range(ny):
            for iz in range(nz):
                for fx, fy, fz in SI_BASIS_FRAC:
                    pos = ((ix + fx) * a, (iy + fy) * a, (iz + fz) * a)
                    si_positions.append(pos)

    # Unique nearest-neighbor Si-Si pairs under PBC. Put O atoms at midpoints.
    nn = a * math.sqrt(3.0) / 4.0
    cutoff = nn * 1.08
    o_positions: List[Vec] = []
    for i in range(len(si_positions)):
        for j in range(i + 1, len(si_positions)):
            d = min_image_delta(si_positions[i], si_positions[j], box)
            if norm(d) < cutoff:
                m = add(si_positions[i], scale(d, 0.5))
                o_positions.append((wrap(m[0], box[0]), wrap(m[1], box[1]), wrap(m[2], box[2])))

    expected_o = 2 * len(si_positions)
    if len(o_positions) != expected_o:
        raise RuntimeError(
            f"Expected {expected_o} bridging O atoms, found {len(o_positions)}. "
            "Try changing lattice constant or cutoff tolerance."
        )

    # Add atoms in type-friendly order: all Si first, then all O.
    for pos in si_positions:
        symbols.append("Si")
        positions.append(pos)
    for pos in o_positions:
        symbols.append("O")
        positions.append(pos)

    # Optional small random displacement to break perfect symmetry.
    if jitter > 0.0:
        new_positions = []
        for x, y, z in positions:
            dx = rng.uniform(-jitter, jitter)
            dy = rng.uniform(-jitter, jitter)
            dz = rng.uniform(-jitter, jitter)
            new_positions.append((wrap(x + dx, box[0]), wrap(y + dy, box[1]), wrap(z + dz, box[2])))
        positions = new_positions

    return symbols, positions, box


def write_xyz(path: Path, symbols: List[str], positions: List[Vec], box: Vec) -> None:
    with path.open("w", encoding="utf-8") as f:
        f.write(f"{len(symbols)}\n")
        f.write(f'Lattice="{box[0]:.10f} 0 0 0 {box[1]:.10f} 0 0 0 {box[2]:.10f}" Properties=species:S:1:pos:R:3 pbc="T T T"\n')
        for sym, (x, y, z) in zip(symbols, positions):
            f.write(f"{sym:2s} {x:16.8f} {y:16.8f} {z:16.8f}\n")


def write_lammps_data(path: Path, symbols: List[str], positions: List[Vec], box: Vec) -> None:
    type_map = {"Si": 1, "O": 2}
    with path.open("w", encoding="utf-8") as f:
        f.write("# beta-cristobalite SiO2 generated by make_beta_cristobalite.py\n\n")
        f.write(f"{len(symbols)} atoms\n")
        f.write("2 atom types\n\n")
        f.write(f"0.0 {box[0]:.10f} xlo xhi\n")
        f.write(f"0.0 {box[1]:.10f} ylo yhi\n")
        f.write(f"0.0 {box[2]:.10f} zlo zhi\n\n")
        f.write("Masses\n\n")
        f.write(f"1 {SI_MASS:.6f} # Si\n")
        f.write(f"2 {O_MASS:.6f} # O\n\n")
        f.write("Atoms # charge\n\n")
        for idx, (sym, (x, y, z)) in enumerate(zip(symbols, positions), start=1):
            f.write(f"{idx:8d} {type_map[sym]:2d} {0.0: .8f} {x:16.8f} {y:16.8f} {z:16.8f} # {sym}\n")


def write_pdb(path: Path, symbols: List[str], positions: List[Vec], box: Vec) -> None:
    # Minimal PDB, useful for PLUMED MOLINFO/SAXS atomistic tests.
    with path.open("w", encoding="utf-8") as f:
        f.write(f"CRYST1{box[0]:9.3f}{box[1]:9.3f}{box[2]:9.3f}{90.0:7.2f}{90.0:7.2f}{90.0:7.2f} P 1           1\n")
        for idx, (sym, (x, y, z)) in enumerate(zip(symbols, positions), start=1):
            # PLUMED/biomolecular PDB parsers are happier if the element column is set.
            f.write(f"ATOM  {idx:5d} {sym:>2s}   SIO A{1:4d}    {x:8.3f}{y:8.3f}{z:8.3f}{1.00:6.2f}{0.00:6.2f}          {sym:>2s}\n")
        f.write("END\n")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--a", type=float, default=7.15, help="beta-cristobalite conventional-cell lattice constant in Angstrom")
    ap.add_argument("--reps", type=int, nargs=3, default=(2, 2, 2), metavar=("NX", "NY", "NZ"))
    ap.add_argument("--jitter", type=float, default=0.0, help="random displacement amplitude in Angstrom")
    ap.add_argument("--seed", type=int, default=12345)
    ap.add_argument("--out-prefix", default="structures/beta_cristobalite_192")
    args = ap.parse_args()

    symbols, positions, box = generate(args.a, tuple(args.reps), args.jitter, args.seed)
    prefix = Path(args.out_prefix)
    prefix.parent.mkdir(parents=True, exist_ok=True)
    write_xyz(prefix.with_suffix(".xyz"), symbols, positions, box)
    write_pdb(prefix.with_suffix(".pdb"), symbols, positions, box)
    write_lammps_data(prefix.with_suffix(".data"), symbols, positions, box)

    print(f"Wrote {len(symbols)} atoms: Si={symbols.count('Si')}, O={symbols.count('O')}")
    print(f"Box: {box[0]:.5f} {box[1]:.5f} {box[2]:.5f} Angstrom")
    print(f"Files: {prefix.with_suffix('.data')}, {prefix.with_suffix('.xyz')}, {prefix.with_suffix('.pdb')}")


if __name__ == "__main__":
    main()
